version: '3.8'

services:
  # Development Frontend
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - eyesante-dev-network

  # Development Nginx (optional)
  nginx-dev:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-dev
    restart: unless-stopped
    networks:
      - eyesante-dev-network
    profiles:
      - nginx

networks:
  eyesante-dev-network:
    driver: bridge

volumes:
  node_modules:
  next_cache: 