-- Create doctor_recommendations table
CREATE TABLE IF NOT EXISTS doctor_recommendations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    visit_session_id BIGINT NOT NULL,
    recommendation_type VARCHAR(50) NOT NULL,
    diagnosis TEXT,
    treatment_plan TEXT,
    medications TEXT,
    follow_up_required BOOLEAN DEFAULT FALSE,
    follow_up_date TIMESTAMP,
    follow_up_notes TEXT,
    referral_required BOOLEAN DEFAULT FALSE,
    referral_to VARCHAR(255),
    referral_reason TEXT,
    surgery_required BOOLEAN DEFAULT FALSE,
    surgery_type VARCHAR(255),
    surgery_notes TEXT,
    lifestyle_recommendations TEXT,
    additional_notes TEXT,
    recommended_by VARCHAR(255),
    recommendation_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) DEFAULT 'system',
    updated_by VARCHAR(100) DEFAULT 'system',
    
    CONSTRAINT fk_doctor_recommendations_visit_session 
        FOREIGN KEY (visit_session_id) REFERENCES patient_visit_sessions(id) ON DELETE CASCADE
);

-- Create index for visit_session_id
CREATE INDEX IF NOT EXISTS idx_doctor_recommendations_visit_session_id 
    ON doctor_recommendations(visit_session_id);

-- Create index for recommendation_type
CREATE INDEX IF NOT EXISTS idx_doctor_recommendations_type 
    ON doctor_recommendations(recommendation_type);
