-- Create emergencies table
CREATE TABLE IF NOT EXISTS emergencies (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    visit_session_id BIGINT NOT NULL,
    emergency_type VARCHAR(50) NOT NULL,
    priority_level VARCHAR(50) NOT NULL,
    chief_complaint TEXT NOT NULL,
    onset_time TIMESTAMP,
    severity_level VARCHAR(50),
    vital_signs_stable BOOLEAN,
    consciousness_level VARCHAR(100),
    pain_level INTEGER,
    allergies VARCHAR(255),
    current_medications TEXT,
    immediate_action_taken TEXT,
    requires_immediate_surgery BOOLEAN DEFAULT FALSE,
    requires_transfer BOOLEAN DEFAULT FALSE,
    transfer_hospital VARCHAR(255),
    transfer_reason TEXT,
    emergency_notes TEXT,
    arrival_time TIMESTAMP,
    treatment_start_time TIMESTAMP,
    stabilized_time TIMESTAMP,
    attended_by VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) DEFAULT 'system',
    updated_by VARCHAR(100) DEFAULT 'system',
    
    CONSTRAINT fk_emergencies_visit_session 
        FOREIGN KEY (visit_session_id) REFERENCES patient_visit_sessions(id) ON DELETE CASCADE
);

-- Create index for visit_session_id
CREATE INDEX IF NOT EXISTS idx_emergencies_visit_session_id 
    ON emergencies(visit_session_id);

-- Create index for emergency_type
CREATE INDEX IF NOT EXISTS idx_emergencies_type 
    ON emergencies(emergency_type);

-- Create index for priority_level
CREATE INDEX IF NOT EXISTS idx_emergencies_priority 
    ON emergencies(priority_level);
