-- Create medication_refills table
CREATE TABLE IF NOT EXISTS medication_refills (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    visit_session_id BIGINT NOT NULL,
    original_prescription_id BIGINT,
    inventory_item_id BIGINT NOT NULL,
    quantity_requested INTEGER,
    quantity_dispensed INTEGER,
    remaining_doses INTEGER,
    refill_reason TEXT,
    patient_compliant BOOLEAN,
    side_effects_reported VARCHAR(255),
    effectiveness_rating INTEGER,
    refill_approved BOOLEAN DEFAULT FALSE,
    approved_by VARCHAR(255),
    approval_date TIMESTAMP,
    dispensed_by VARCHAR(255),
    dispense_date TIMESTAMP,
    next_refill_date TIMESTAMP,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) DEFAULT 'system',
    updated_by VARCHAR(100) DEFAULT 'system',
    
    CONSTRAINT fk_medication_refills_visit_session 
        FOREIGN KEY (visit_session_id) REFERENCES patient_visit_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_medication_refills_inventory_item 
        FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE RESTRICT
);

-- Create index for visit_session_id
CREATE INDEX IF NOT EXISTS idx_medication_refills_visit_session_id 
    ON medication_refills(visit_session_id);

-- Create index for inventory_item_id
CREATE INDEX IF NOT EXISTS idx_medication_refills_inventory_item_id 
    ON medication_refills(inventory_item_id);

-- Create index for refill_approved
CREATE INDEX IF NOT EXISTS idx_medication_refills_approved 
    ON medication_refills(refill_approved);
