-- Create reviews table
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    visit_session_id BIGINT NOT NULL,
    previous_visit_id BIGINT,
    review_type VARCHAR(50) NOT NULL,
    treatment_compliance BOOLEAN,
    symptom_improvement BOOLEAN,
    side_effects_experienced VARCHAR(255),
    current_symptoms TEXT,
    treatment_effectiveness_rating INTEGER,
    recommendation_changes BOOLEAN,
    new_recommendations TEXT,
    follow_up_required BOOLEAN DEFAULT FALSE,
    follow_up_date TIMESTAMP,
    review_notes TEXT,
    reviewed_by VARCHAR(255),
    review_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) DEFAULT 'system',
    updated_by VARCHAR(100) DEFAULT 'system',
    
    CONSTRAINT fk_reviews_visit_session 
        FOREIGN KEY (visit_session_id) REFERENCES patient_visit_sessions(id) ON DELETE CASCADE
);

-- Create index for visit_session_id
CREATE INDEX IF NOT EXISTS idx_reviews_visit_session_id 
    ON reviews(visit_session_id);

-- Create index for review_type
CREATE INDEX IF NOT EXISTS idx_reviews_type 
    ON reviews(review_type);

-- Create index for previous_visit_id
CREATE INDEX IF NOT EXISTS idx_reviews_previous_visit_id 
    ON reviews(previous_visit_id);
